quarkus.application.name=quarkus-smallrye-openapi-3-31-4-bug
# Swagger
quarkus.swagger-ui.path=/docs
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.title=${quarkus.application.name}: API Documentation